FROM maven:3.3.9-jdk-8
MAINTAINER Jonas Holtorf <Jonas.Holtorf@4wits.de>

# NOT DONE!!!


#"-agentpath:/jrebel/lib/libjrebel64.so", "-Drebel.log.file=/jrebel.log",
#CMD ["java", "-Xdebug","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=7000", "-Xmx200m", "-jar", "/app/app.jar"]
WORKDIR /app
CMD ["mvn","-Pdev","-Dfork=true", "-Drun.jvmArguments=-Xmx256m -Xms192m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=7000" , "spring-boot:run"]

#CMD ["java", "-javaagent:/jrebel/jrebel.jar", "-Drebel.log.file=/jrebel.log", "-jar", "/app/app.jar"]

EXPOSE 8080
EXPOSE 7000
