FROM alopcas4wits/full-pdflatex-dev:1.0
MAINTAINER Jonas Holtorf <Jonas.Holtorf@4wits.de>

WORKDIR /app
CMD ["mvn","-Pdev","-Dfork=true", "-Drun.jvmArguments=-Xmx128m -Xms64m -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=7000" , "spring-boot:run"]

EXPOSE 8080
EXPOSE 7000
